AWSTemplateFormatVersion: "2010-09-09"
Description: Child stack - orders table
Parameters:
  Env:
    Type: String
Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub orders-${Env}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
Outputs:
  TableName:
    Value: !Ref OrdersTable
